# vi: set ft=yml
# -*- coding: utf-8 -*-

version: '3'

services:
  minio1:
    image: minio/minio:RELEASE.2021-01-16T02-19-44Z
    hostname: minio1
    volumes:
      - /minio:/export
    networks:
      - minio_distributed
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.minio1.rule=Host(`minio.local`)"
        - "traefik.http.routers.minio1.entrypoints=web"
        - "traefik.http.services.minio1.loadbalancer.server.port=9000"
        - "traefik.http.routers.minio1-tls.rule=Host(`minio.local`)"  
        - "traefik.http.routers.minio1-tls.entrypoints=webtls"
        - "traefik.http.routers.minio1-tls.tls.certresolver=letsencryptresolver"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    environment:
        MINIO_ROOT_USER: juancarlos
        MINIO_ROOT_PASSWORD: qwerty123
    command: server http://minio{1...4}/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2021-01-16T02-19-44Z
    hostname: minio2
    volumes:
      - /minio:/export
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
    environment:
        MINIO_ROOT_USER: juancarlos
        MINIO_ROOT_PASSWORD: qwerty123
    command: server http://minio{1...4}/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2021-01-16T02-19-44Z
    hostname: minio3
    volumes:
      - /minio:/export
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio3==true
    environment:
        MINIO_ROOT_USER: juancarlos
        MINIO_ROOT_PASSWORD: qwerty123
    command: server http://minio{1...4}/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2021-01-16T02-19-44Z
    hostname: minio4
    volumes:
      - /minio-2:/export
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio4==true
    environment:
        MINIO_ROOT_USER: juancarlos
        MINIO_ROOT_PASSWORD: qwerty123
    command: server http://minio{1...4}/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  minio_distributed:
    driver: overlay
  traefik:
    external: true
